# Site settings
title: Sevena Skeels
email: sskeels@knights.ucf.edu
description: > # this means to ignore newlines until "baseurl:"
  Find out all about Sevena Skeels! She likes to program, solve problems, explore Skyrim, and be employed! See inside for resume and portfolio!
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.sevenaskeels.com" # the base hostname & protocol for your site
github_username:  jellybeanfiend
collections:
  - social-media
exclude:
 - Gemfile.lock
 - Gemfile
 - README
gems:
 - octopress-autoprefixer

# Build settings
markdown: kramdown
